# Generated by Django 5.1.5 on 2025-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('write_date', models.DateTimeField()),
                ('publish_date', models.DateField()),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
